name: container_server_example
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path:
  crypto:

  uuid:
  shelf: ^1.1.4
  jaguar_jwt: ^3.0.0
  mongo_dart: ^0.7.0+2
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0

#scripts:
#  dev: webdev serve --auto restart
#  build: webdev build
#  dev_server:
#    - $build
#    - dart bin/server.dart
#  deploy: git push heroku master

dev_dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: ^3.0.0
  pedantic: ^1.9.0
  http: ^0.13.0
  lints: ^1.0.0
  test: ^1.15.0
  test_process: ^2.0.0
