name: chasseur_api_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.1.0
  jaguar_jwt: ^3.0.0
  crypto:
  mailer: ^5.0.1
  mongo_dart: ^0.7.0+2
  get_it: ^7.2.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
